In [11]:
import numpy as np


def problem_4_part_2():
    for i in range(1, 4):
        print(f"Matrix {i}")
        
        matrix_found = False
        while not matrix_found:
            A = np.random.randint(-10, 11, size=(3, 3))
            if np.linalg.det(A) != 0:
                matrix_found = True
        
        print("Generated Matrix:")
        print(A)
        
        A_inv = np.linalg.inv(A)
        print("\nInverse Matrix:")
        print(A_inv)
        
        identity_check = A @ A_inv
        
        print("\nProduct (Matrix * Inverse) - Identity Check:")
        print(np.round(identity_check, decimals=10))

if __name__ == "__main__":
    problem_4_part_2()

Matrix 1
Generated Matrix:
[[-10  -3  -4]
 [  7  -3 -10]
 [  0   7  -1]]

Inverse Matrix:
[[-0.0771  0.0327 -0.019 ]
 [-0.0074 -0.0106  0.1352]
 [-0.0517 -0.0739 -0.0539]]

Product (Matrix * Inverse) - Identity Check:
[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
Matrix 2
Generated Matrix:
[[ -8  -4   5]
 [  5   9   6]
 [ -9 -10   5]]

Inverse Matrix:
[[-0.2846  0.0813  0.187 ]
 [ 0.2141 -0.0136 -0.1978]
 [-0.084   0.1192  0.1409]]

Product (Matrix * Inverse) - Identity Check:
[[ 1.  0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]
Matrix 3
Generated Matrix:
[[ 1 -6 -6]
 [-2 -2 -8]
 [ 8  5  5]]

Inverse Matrix:
[[ 0.0943  0.      0.1132]
 [-0.1698  0.1667  0.0629]
 [ 0.0189 -0.1667 -0.044 ]]

Product (Matrix * Inverse) - Identity Check:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
